using System;
using System.Collections.Generic;
using System.Text;

namespace IntelligentAnalysis
{
    class WordList
    {
        public static readonly string _list =
            " me" +
            " ii" +
            " iii" +
            " iv" +
            " vi" +
            " vii" +
            " viii" +
            " ix" +
            " xi" +
            " xii" +
            " xiii" +
            " xiv" +
            " xv" +
            " will" +
            " from" +
            " are" +
            " were" +
            " been" +
            " somehow" +
            " reuters" +
            " him" +
            " her" +
            " us" +
            " them" +
            " you" +
            " he" +
            " she" +
            " it" +
            " we" +
            " they" +
            " what" +
            " who" +
            " me" +
            " him" +
            " her" +
            " it" +
            " us" +
            " you" +
            " them" +
            " whom" +
            " mine" +
            " yours" +
            " his" +
            " hers" +
            " ours" +
            " theirs" +
            " this" +
            " that" +
            " these" +
            " those" +
            " who" +
            " whom" +
            " which" +
            " what" +
            " whose" +
            " whoever" +
            " whatever" +
            " whichever" +
            " whomever" +
            " who" +
            " whom" +
            " whose" +
            " which" +
            " that" +
            " what" +
            " whatever" +
            " whoever" +
            " whomever" +
            " whichever" +
            " myself" +
            " yourself" +
            " himself" +
            " herself" +
            " itself" +
            " ourselves" +
            " themselves" +
            " myself" +
            " yourself" +
            " himself" +
            " herself" +
            " itself" +
            " ourselves" +
            " themselves" +
            " each" +
            " other" +
            " another" +
            " anything" +
            " everybody" +
            " another" +
            " each" +
            " few" +
            " many" +
            " none" +
            " some" +
            " all" +
            " also" +
            " any" +
            " anybody" +
            " anyone" +
            " everyone" +
            " everything" +
            " noone" +
            " nobody" +
            " nothing" +
            " others" +
            " several" +
            " somebody" +
            " someone" +
            " something" +
            " most" +
            " enough" +
            " little" +
            " more" +
            " both" +
            " either" +
            " neither" +
            " much" +
            " such" +
            " about" +
            " above" +
            " across" +
            " after" +
            " ago" +
            " at" +
            " below" +
            " by" +
            " Down" +
            " During" +
            " For" +
            " From" +
            " in" +
            " into" +
            " off" +
            " on" +
            " over" +
            " past" +
            " through" +
            " to" +
            " under" +
            " until" +
            " up" +
            " with" +
            " for" +
            " and" +
            " nor" +
            " but" +
            " or" +
            " yet" +
            " so" +
            " there" +
            " as" +
            " once" +
            " after" +
            " though" +
            " before" +
            " even" +
            " if" +
            " when" +
            " just" +
            " now" +
            " that" +
            " since" +
            " that" +
            " though" +
            " until" +
            " whenever" +
            " whereas" +
            " wherever" +
            " which" +
            " rather" +
            " than" +
            " then" +
            " who";
    }
}
